import { NextRequest, NextResponse } from "next/server";
import { callGemini } from "@/lib/gemini";

/**
 * POST /api/ml/detect
 *
 * Body:   { text: string }
 * Returns: { ai_probability: number, verdict: string, reason: string }
 *
 * Analyses the supplied text and estimates the likelihood it was
 * generated by an AI model.
 */

interface DetectRequest {
  text: string;
}

interface DetectResponse {
  ai_probability: number; // 0–100
  verdict: string;        // e.g. "Likely AI-generated"
  reason: string;         // short explanation
}

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as DetectRequest;

    if (!body.text || typeof body.text !== "string") {
      return NextResponse.json(
        { error: "Request body must include a non-empty `text` string." },
        { status: 400 }
      );
    }

    const prompt = `
You are an AI-content detection expert.

Analyse the following text and determine the probability that it was written by an AI (not a human).

Return ONLY valid JSON (no markdown fences) in exactly this shape:
{
  "ai_probability": <integer 0-100>,
  "verdict": "<one short label, e.g. 'Likely AI-generated' | 'Likely Human-written' | 'Uncertain'>",
  "reason": "<one or two sentences explaining the key signals>"
}

Text to analyse:
"""
${body.text}
"""
`.trim();

    const result = await callGemini<DetectResponse>(prompt);

    return NextResponse.json(result, { status: 200 });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
