import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import OpenAI from 'openai';
import { createServer } from 'http';
import { Server } from 'socket.io';

dotenv.config();

const app = express();
const httpServer = createServer(app);
const io = new Server(httpServer, {
  cors: { origin: '*' }
});

const prisma = new PrismaClient();
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY || 'missing' });
app.use(cors());
app.use(express.json());

// Real-time Socket Connection
io.on('connection', (socket) => {
  console.log('Client connected:', socket.id);
  
  // Simulate a real-time event (e.g. someone liked your post)
  setTimeout(() => {
    socket.emit('notification', {
      id: Date.now().toString(),
      type: 'social',
      title: 'New Like',
      body: 'Sneha Iyer liked your achievement post! (+5 XP)',
      xp: 5,
      createdAt: new Date().toISOString()
    });
  }, 10000); // 10s after connection
  
  socket.on('disconnect', () => {
    console.log('Client disconnected:', socket.id);
  });
});

const JWT_SECRET = process.env.JWT_SECRET || 'fallback-secret';

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', message: 'SkillSphere API is running' });
});

// AUTH
app.post('/api/auth/login', async (req, res) => {
  const { email, password } = req.body;
  try {
    const user = await prisma.user.findUnique({ where: { email } });
    if (!user) return res.status(404).json({ error: 'User not found' });
    
    // In production, compare password: await bcrypt.compare(password, user.password)
    // For local dev with seed data, just bypass for ease of demo if password matches
    
    const token = jwt.sign({ userId: user.id, role: user.role }, JWT_SECRET, { expiresIn: '7d' });
    
    // Parse JSON fields
    const formattedUser = {
      ...user,
      interests: JSON.parse(user.interests),
      badges: JSON.parse(user.badges)
    };
    
    res.json({ accessToken: token, user: formattedUser });
  } catch (err) {
    res.status(500).json({ error: 'Login failed' });
  }
});

// COURSES
app.get('/api/courses', async (req, res) => {
  try {
    const courses = await prisma.course.findMany({
      include: { progress: true }
    });
    res.json({ data: courses });
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch courses' });
  }
});

// JOBS
app.get('/api/jobs', async (req, res) => {
  try {
    const jobs = await prisma.job.findMany();
    const formattedJobs = jobs.map(j => ({...j, requirements: JSON.parse(j.requirements)}));
    res.json({ data: formattedJobs });
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch jobs' });
  }
});

// AI - Content Detector
app.post('/api/ai/detect', async (req, res) => {
  const { text } = req.body;
  if (!text) return res.status(400).json({ error: 'Text is required' });

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: "You are an AI content detector. Analyze the given text and determine the probability (0-100%) that it was generated by an AI. Respond ONLY with a JSON object in this exact format: {\"aiProbability\": 85, \"reasoning\": \"Brief 1 sentence explanation\"}." },
        { role: "user", content: text }
      ],
      response_format: { type: "json_object" }
    });
    
    const result = JSON.parse(response.choices[0].message.content || '{}');
    res.json(result);
  } catch (err: any) {
    // Fallback if OpenAI key is invalid or missing
    console.log("OpenAI API failed (likely missing key), using fallback.", err.message);
    const mockProb = text.length > 200 ? 82 : 14;
    res.json({ 
      aiProbability: mockProb, 
      reasoning: "Mock response: The text structure and vocabulary variance suggest this probability." 
    });
  }
});

// AI - Mock Interview
app.post('/api/ai/interview', async (req, res) => {
  const { topic, pastMessages } = req.body;
  
  try {
    const messages = [
      { role: "system", content: `You are an expert technical interviewer for the topic: ${topic || 'Software Engineering'}. Ask exactly ONE challenging interview question. If the user provided an answer in past messages, give brief constructive feedback on their answer before asking the next question. Keep responses under 4 sentences.` },
      ...(pastMessages || [])
    ];

    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: messages as any
    });
    
    res.json({ response: response.choices[0].message.content });
  } catch (err: any) {
    console.log("OpenAI API failed (likely missing key), using fallback.", err.message);
    res.json({ 
      response: `[Mock AI] That's a good point. Now, can you explain how you would optimize a highly concurrent system dealing with race conditions in ${topic || 'this domain'}?` 
    });
  }
});

const PORT = process.env.PORT || 3001;

httpServer.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
